### PR TITLE
improve component chapter

### PR DESCRIPTION
**Pull request by tronta**
as discussed here:
https://github.com/Relm4/book/issues/30

Not sure who should be reviewer

### CODE REVIEW

**Review by AaronErhardt — CHANGES_REQUESTED** [review]
Can you use backticks around the traits? That makes the traits `better visible` and would be more consistent with the rest of the book.

**Comment by tronta** [comment]
Thanks for paying attention. I was too tiered yesterday…

**Comment by AaronErhardt** [comment]
Thanks!

**Comment by tronta** [comment]
Sorry for asking again… unfortunately I only have time to work on it when I'm tiered :cry:  

For every implementation of SimpleComponent Relm4 will also implement Component automatically. You just need to implement one of them and your type will implement Component either way. This is called [blanket implementation](https://doc.rust-lang.org/book/ch10-02-traits.html#using-trait-bounds-to-conditionally-implement-methods) and is used for traits like From in the standard library as well.

Is this part "You just need to implement one of them and your type will implement Component either way. " really true?
When one implements the Component trait, I would assume, that the SimpleTrait is not implemented, as it would result in loss of information. Maybe I still didn't get it…

**Comment by AaronErhardt** [comment]
Yes, it only works in one direction. But that's ok because we just need Component, SimpleComponent is just a helper trait.
If we needed both that'd be different as with From and Into where you always should implement From to get Into on top because implementing Into doesn't give you From.

**Comment by tronta** [comment]
But then I do not understand why we need the second sentences… why not just:

For every implementation of SimpleComponent Relm4 will also implement Component automatically. This is called [blanket implementation](https://doc.rust-lang.org/book/ch10-02-traits.html#using-trait-bounds-to-conditionally-implement-methods) and is used for traits like From in the standard library as well.

it seams to make it unnecessary complicated.

**Comment by AaronErhardt** [comment]
Yes, that might be better. The second sentence doesn't really add any information.

**Pull request merged**
